apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot 
  janus-idp.io/tekton: chatbot
  backstage.io/kubernetes-id: chatbot
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: chatbot
resources: 
- application-dev.yaml